国・都道府県・河川で取得するデータを変更する
Noah0x0/lambda-waterLevelAPI pull request #10
Opened 2017-08-15 15:37 UTC by runble1

国・都道府県・河川の引数から該当データを取得するよう修正

2017-08-16 14:29 UTC, mesh1nek0x0 requested changes
質問記載しました〜

2017-08-16 14:29 UTC, mesh1neko commented on lambda_function.py
> +    list = client.list_objects(
ASK
これって全件取得になりませんか？！
データが増えれば増えるほど、メモリが必要になるのでは？と思っています。

prefixで日付か時間あたりまでいれて絞ってもいいかも

2017-08-16 14:29 UTC, mesh1neko commented on lambda_function.py
> +        json_dict = get_waterlevel(target_key)
ASK
target_keyが空の場合って大丈夫ですか...？

2017-08-16 15:14 UTC, runble1 commented on lambda_function.py
> +    list = client.list_objects(
一旦リクエストされた時点の年月を prefix に追記しました。
UTCとJSTなどを考慮して、日付レベルで取得できるようにしたいと思います、今後。

2017-08-16 15:19 UTC, mesh1nek0x0 approved these changes
+1

2017-08-16 15:20 UTC, mesh1neko commented
[![LGTM](http://lgtm.in/p/eHgmkJhcq)](http://lgtm.in/i/eHgmkJhcq)

2017-08-16 15:26 UTC, runble1 commented on lambda_function.py
> +        json_dict = get_waterlevel(target_key)
ぜんぜん大丈夫じゃないです。
まったく意味のない文字列を送り込まれた場合に例外発生します。
API Gateway側で 400エラー を返したほうがいいですかね？プログラム側で制御したほうがいいですかね？

2017-08-16 15:39 UTC, mesh1neko commented on lambda_function.py
> +        json_dict = get_waterlevel(target_key)
@runble1 取り急ぎデフォルトの値を返すか、値なしで返すか、400エラーで返すのがよいかと。
ベストは400エラー

2017-08-18 14:20 UTC, runble1 commented
以下2つを対応しました。
1. 取得するS3の一覧を年月で絞る対応
2. 無効なURLを指定された際の 400 BadRequest を返却

2017-08-19 05:52 UTC, mafuyuk commented on README.md
> +Endpoint : /production/water-level?country="japan"&prefectures="tokyo"&river="arakawa"
path違います

2017-08-19 05:58 UTC, mesh1nek0x0 approved these changes
+1

2017-08-19 06:20 UTC, merged